name: Ne.app RSL Test CI (Develop, SPARC)

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build CI Packages
      run: sudo apt update -y && sudo apt install build-essential cmake
    - name: Build CI for RSL
      run: make all ARCH=sparc
    - name: Install CI for RSL
      run: sudo make install
